### PR TITLE
Add LizFest 2020 as Mock Event

### PR DESCRIPTION
**Pull request by ElizabethN**
Signed-off-by: Elizabeth Barron <elizabeth@naramore.net>

# Event Submission

> ❗Note: Go through the [Event Criteria](../submission/event-criteria.md) to know acceptable Event metric format for CHAOSS Badging.

## Requirements

- Link to the Event Website: https://lizfest2020.com
- Link to your Event Code of Conduct: https://lizfest2020.com/code-of-conduct

## Speaker Demographics

- [x] This event commits to Speaker Diversity & Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` We have an anonymous submission review process but we ask for demographic information in the submission process.
  - `Q` Give the link for the page related to Speaker Demographics if available.
  - `A` http://lizfest2020.com/speakers
 
## Attendee Demographics

- [x] This event commits to Attendee Diversity & Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` We ask for demographic information in the registration process, but it is voluntary.
  - `Q` Give the link for the page related to Attendee Demographics if available.
  - `A` n/a

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
    - `Q` Provide link for Event Code of Conduct.
    - `A` https://lizfest2020.com/code-of-conduct
    - `Q` Is the code of conduct posted at Event venue?
    - `A` Yes.

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
    - `Q` Link to the page containing information about Diversity Access Tickets.
    - `A` https://lizfest2020.com/diversity
    - `Q` How many different types of diversity access tickets are available for the event?
    - `A` 12
    - `Q` What are the criteria for qualifying for a diversity access ticket?
    - `A` Accessibility/ability, race/ethnicity, gender identification, student status, over 60 in age, financial need

## Family Friendliness
- [x] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Yes.
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` A kids track, family social events (no alcohol), the venue is at a water park, extra tickets at the hotel before and after the event are available, a dedicated private parents' nursing area provided, family game night
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A` https://lizfest2020.com/families

### CODE REVIEW

**Comment by bistaastha** [comment]
Hi @ElizabethN , looks like your event is committed to all five Event metrics. Can you check all the corresponding boxes so that it's easy to see which metrics match?
Thanks!

**Comment by ElizabethN** [comment]
@bistaastha Done!

**Comment by germonprez** [comment]
SAMPLE: 

I was not able to access the code of conduct via the link provided. Could you please double check the link? 

The speaker demographics page provided is only showing the current speakers. Could you please provide a link that would show, at minimum, the summary demographic information provided by the speakers? 

Like speaker demographics, is there a way to report this data -- at least as a summary page? 

I look forward to your responses and thanks for applying for a CHAOSS D&I Events Badge.

**Comment by Nebrethar** [comment]
I am closing this Pull Request to clean up before the 2nd pilot test., Thank you for being a part of the Badging Project!

**Pull request closed without merging**
