### PR TITLE
Add reviewers and remove redundant version numbers

### PR DESCRIPTION
**Pull request by Nebrethar**
This PR is a result of proposed website updates for the Badging Initiative. The first step I'm taking is to propose that we add reviewer handles to the badge list. Let me know what you think!

### CODE REVIEW

**Review by bistaastha — APPROVED** [review]
LGTM :)

**Comment by Nebrethar** [comment]
Needs to be updated with new reviews. Changes will take place if this is accepted

**Comment by Nebrethar** [comment]
PR needs updates, will recieve sometime october 1-5

**Comment by Nebrethar** [comment]
PR is updated with the latest reviews as of Sept 28, 2021

**Comment by Nebrethar** [comment]
This change was performed manually.

There was too much to change on this branch and no community pushback during the freeze.

Thanks yall!

**Pull request closed without merging**
