### PR TITLE
Add Mock event 3

### PR DESCRIPTION
**Pull request by bistaastha**
---
name: Mock Event 3
about: An event submission for D&I badging evaluation
title: ''
labels: event
assignees: ''
---

# Event Submission

## Attendee Demographics

Metric Question: _How diverse and inclusive are the attendees?_

### Section 1

`Q` Are the attendee demographics of the event measured?

`A` Yes

`Q` If the previous answer is yes, what is the process for measuring attendee demographics?

`A` Attendee demographics are asked during registration. We ask questions about where they are traveling from, and we also include optional questions about their gender and ethnicity. All this data is taken in through our registration Google form.

### Section 2

`Q` Please provide a statement on the event's commitment to Attendee Diversity & Inclusion.

`A` The event commits to Attendee Diversity & Inclusion.

## Code of Conduct at Event

Metric Question: _How does the Code of Conduct for the event support diversity and inclusion?_

### Section 1

`Q` Does the event website host an event Code of Conduct?

`A` Yes

### Section 2

`Q` Is the Code of Conduct posted at the event?

`A` No

`Q` Does the Event Code of Conduct have a clear avenue for reporting violations at the event?

`A` Yes

`Q` Does the Event Code of Conduct OR event website provide information about possible ways to provide support to victims of inappropriate behavior?

`A` Yes

### Section 3:

`Q` Please provide a statement on the event's commitment to its Event Code of Conduct

`A` The event commits to Event Code of Conduct.

## Diversity Access Tickets

Metric Question: _How are Diversity Access Tickets used to support diversity and inclusion for an event?_

### Section 1

`Q` Are numbers from previous conferences displayed on the event website about how many diversity access tickets were used?

`A` No

`Q` Are regular attendees encouraged to sponsor diversity access tickets?

`A` Yes

`Q` Are sponsors of diversity access tickets named?

`A` Yes

`Q` How many different types of diversity access tickets are available for the event?

`A` We offer diversity access tickets to only students.

`Q` What is the price difference between regular and admission with diversity access tickets?

`A` The price of the diversity access ticket is 10% of the regular price.

`Q` What are the criteria for qualifying for a diversity access ticket?

`A` Students need to show proof of enrollment from their school/university. We kept 100 student tickets for this event.

### Section 2

`Q` Please provide a statement on the event's commitment to Diversity Access Tickets.

`A` This event commits to Diversity Access Tickets.

## Family Friendliness

Metric Question: _How does enabling families to attend together support diversity and inclusion of the event?_

### Section 1

`Q` Does the conference promote activities for children and youth? If the answer is yes, provide proof.

`A` No

`Q` Does the conference promote family-oriented activities? If the answer is yes, provide proof.

`A` No

`Q` Does the conference explicitly invite attendees to bring their children? If the answer is yes, provide proof.

`A` No

### Section 2

`Q` Please provide a statement on the event's commitment to Family Friendliness.

`A` This event does not commit to Family Friendliness.

## Speaker Demographics

Metric Question: _How well does the speaker lineup for the event represent a diverse set of demographics and can be improved in the future?_

### Section 1

`Q` Are the speaker demographics of your event measured?

`A` Yes

`Q` If the previous answer is yes, what is the process for measuring speaker demographics?

`A` We have a separate survey to fill up for speaker demographics after the acceptance of CFPs. They are asked similar questions as the attendees.

### Section 2

`Q` Please provide a statement on your event's commitment to Speaker Diversity & Inclusion.

`A` This event commits to Speaker Diversity and Inclusion.

### CODE REVIEW

**Comment by germonprez** [comment]
Thanks for doing this @bistaastha

**Comment by germonprez** [comment]
Make sure to document your work here: 
https://github.com/chaoss/governance/blob/master/GSoC-interest.md

This way we can more easily track applications.

**Comment by bistaastha** [comment]
@germonprez I just found out that a PR and a draft PR are two separate things :woman_facepalming: . Should I make a draft PR for the same?

**Comment by germonprez** [comment]
What you've done is great! Thanks.

**Comment by Nebrethar** [comment]
I am closing this Pull Request to clean up before the 2nd pilot test., Thank you for being a part of the Badging Project!

**Pull request closed without merging**
